### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by lintstar** [zyylhn/zscan#2]
### MAC
```
$ ./zscan all -H 192.168.8.1/24 --ping --log

Mode:all
Start time:2021-11-29 10:12:37
The number of threads:100
Time delay:3s
Traget:192.168.8.1/24
Verbose:Don't show verbose
Ping befor portscan
Save scan log in log.txt


=========================living ip result list==========================
[ping] Find '192.168.8.1' aliving
[ping] Find '192.168.8.123' aliving
[ping] Find '192.168.8.146' aliving
[ping] Find '192.168.8.101' aliving
[ping] Find '192.168.8.121' aliving
[ping] Find '192.168.8.140' aliving
[ping] Find '192.168.8.155' aliving
[ping] Find '192.168.8.159' aliving
[ping] Find '192.168.8.166' aliving
[ping] Find '192.168.8.167' aliving
[ping] Find '192.168.8.255' aliving
A total of 11 IP addresses were discovered
Find port 192.168.8.167:22
Start burp ssh : 192.168.8.167:22
Find port 192.168.8.1:53
Find port 192.168.8.1:80
Find port 192.168.8.159:80
Find port 192.168.8.121:135
Find port 192.168.8.146:135
Find port 192.168.8.159:135
Find port 192.168.8.166:135
panic: runtime error: slice bounds out of range [:-1]

goroutine 723 [running]:
zscan/cmd.oxidIpInfo({0x173a800, 0xc00061a008})
	/Users/zyy/zscan/cmd/winscan.go:519 +0x492
zscan/cmd.Connectall({0xc000920270, 0xc000718300}, 0x87)
	/Users/zyy/zscan/cmd/all.go:139 +0xd45
zscan/cmd.(*PortScan).Startscan(0xc00017e780)
	/Users/zyy/zscan/cmd/ps.go:114 +0x14f
created by zscan/cmd.(*PortScan).Run
	/Users/zyy/zscan/cmd/ps.go:83 +0x6d
```
### Windows
```
C:\Users\Desktop>zscan_win_x64.exe all -H 192.168.8.1/24 --ping --log

Mode:all
Start time:2021-11-29 10:10:41
The number of threads:100
Time delay:3s
Traget:192.168.8.1/24
Verbose:Don't show verbose
Ping befor portscan
Save scan log in log.txt


=========================living ip result list==========================
[ping] Find '192.168.8.1' aliving
[ping] Find '192.168.8.123' aliving
[ping] Find '192.168.8.121' aliving
[ping] Find '192.168.8.140' aliving
[ping] Find '192.168.8.155' aliving
[ping] Find '192.168.8.146' aliving
[ping] Find '192.168.8.159' aliving
[ping] Find '192.168.8.167' aliving
[ping] Find '192.168.8.168' aliving
[ping] Find '192.168.8.166' aliving
A total of 10 IP addresses were discovered
Find port 192.168.8.167:22
Start burp ssh : 192.168.8.167:22
Find port 192.168.8.1:53
Find port 192.168.8.1:80
Find port 192.168.8.159:80
Find port 192.168.8.121:135
Find port 192.168.8.146:135
Find port 192.168.8.168:135
panic: runtime error: slice bounds out of range [:-1]

goroutine 598 [running]:
zscan/cmd.oxidIpInfo({0x10acca0, 0xc0003ae078})
        /Users/zyy/zscan/cmd/winscan.go:519 +0x492
zscan/cmd.Connectall({0xc0004105b0, 0xc0005321b0}, 0x87)
        /Users/zyy/zscan/cmd/all.go:139 +0xd45
zscan/cmd.(*PortScan).Startscan(0xc0002ca6e0)
        /Users/zyy/zscan/cmd/ps.go:114 +0x14f
created by zscan/cmd.(*PortScan).Run
        /Users/zyy/zscan/cmd/ps.go:83 +0x6d
```

**Comment by zyylhn** [comment]
感谢

**Comment by zyylhn** [comment]
已经改掉了

**Comment by lintstar** [comment]
辛苦师傅 push 下 ~

**Comment by zyylhn** [comment]
已经push了，感谢
